### ISSUE TITLE
Question: Why only 100 objects are retrieved from the AWS API?

### ISSUE THREAD

**Issue by GeorgiMateev** [shinsaka/fluent-plugin-elb-log#27]
Hello,
I was looking at the code and saw that get_object_list function calls the AWS API with maxKeys=100 and prefix=[myPrefix]. In the bucket there are potentionally hundreds of thousands of objects spread across partitions like /year/month/day. I didn't saw any logic for calculating the correct partition e.g. the day when the call is executed and provide this partition as a prefix. There is also no logic for implementing paging with the api. Is this intentional or it is a bug? If this is a flaw, a big part of the stored data won't be ingested.
Thanks.

**Comment by shinsaka** [comment]
Hello @GeorgiMateev,
Thank you for your question.

This program code can all item-key in bucket.
"100" means get 100 contents records with one network request.
see testing code below:
https://gist.github.com/shinsaka/c0a17f5859eea8b64c3d3b85fb426b6a

memo:
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#list_objects-instance_method

Best,

**Comment by GeorgiMateev** [comment]
Hi,
Yes, it's requesting 100 items and that's exactly the issue: there could be many more than 100 items in the bucket.
I haven't seen any logic in the code to traverse all objects by using continuation token return by list_objects.
Can you please point me where in the code you are traversing all available objects in the bucket?
Thanks.
