### ISSUE TITLE
Unknown input plugin 'elb_log'

### ISSUE THREAD

**Issue by amanmahajan26** [shinsaka/fluent-plugin-elb-log#39]
After updating the conf file with the required values, when I restart the docker container, it's crashing. In the logs I am seeing this error: `[error]: config error file="/fluentd/etc/fluentd.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'elb_log'.`

**Comment by amanmahajan26** [comment]
I had installed the plugin locally, it was not visible to the docker container. So I created a new docker image with plugin and it worked fine.

**Comment by shinsaka** [comment]
@amanmahajan26  Thank you for your report!

**Comment by meta-morpho-sys** [comment]
Hey amanmahajan26, I am having similar issues. Can you please share an example of the new docker image with the plugin?
